const API_BASE_URL_DEVELOPMENT = "https://localhost:7011";

const ENDPOINTS = {
    GET_ALL_LIBRARIES: 'api/libraries',
    GET_LIBRARY_BY_ID: 'api/libraries/libraryId',
    GET_ALL_USERS: 'api/users',
    GET_USER_BY_ID: 'api/users/userId',
    //GET_ALL_RESERVATIONS: 'api/reservations',
    //GET_RESERVATION_BY_ID: 'api/reservations/reservationId',
    //GET_ALL_EBOOKS: 'api/ebooks',
    //GET_EBOOK_BY_ID: 'api/ebooks/ebooksId',
    GET_ALL_CITIES: 'api/cities',
    GET_CITY_BY_ID: 'api/cities/cityId',
    GET_ALL_BOOKS: 'api/books',
    GET_BOOK_BY_ID: 'api/books/bookId',
    TO_HOME: 'api/#',
    TO_LOGIN: 'api/login',
    TO_REGISTER: 'api/register'
}
const development = {
    API_URL_GET_ALL_LIBRARIES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_LIBRARIES}`,
    API_URL_GET_LIBRARY_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_LIBRARY_BY_ID}`,
    API_URL_GET_ALL_USERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USERS}`,
    API_URL_GET_USER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_BY_ID}`,
    //API_URL_GET_ALL_RESERVATIONS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_RESERVATIONS}`,
    //API_URL_GET_RESERVATION_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_RESERVATION_BY_ID}`,
    //API_URL_GET_ALL_EBOOKS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_EBOOKS}`,
    //API_URL_GET_EBOOK_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_EBOOK_BY_ID}`,
    API_URL_GET_ALL_CITIES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_CITIES}`,
    API_URL_GET_CITY_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_CITY_BY_ID}`,
    API_URL_GET_ALL_BOOKS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_BOOKS}`,
    API_URL_GET_BOOK_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_BOOK_BY_ID}`,
    API_URL_GET_AFTER_REGISTER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_LIBRARIES}`,
    API_URL_LOGIN: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TO_LOGIN}`,
    API_URL_REGISTER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.TO_REGISTER}`
    //API_URL_CREATE_LIBRARY: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_LIBRARIES}`
};



const Constants = development;

export default Constants;